### PR TITLE
messari price library uploaded

### PR DESCRIPTION
**Pull request by arslanbekzhaparov**

### CODE REVIEW

**Comment by arslanbekzhaparov** [comment]
Brought Messarie's price lib with all the requested changes:

From discussion:

1. bring in their entire prices folder - COMPLETED
2. make the 2 exposed function in index.ts take in Token instead of the address - COMPLETED
3. make the 2 exposed function in index.ts return BigDecimals - COMPLETED
4. Only update price if Token price hasn’t been updated that block
    1. Means you also need to store the last block price was updated in the Token object - Completed
5. Store which oracle the token got its price from in Token - COMPLETED

**Comment by spennyp** [comment]
Says there are a bunch of empty files, did you forget to add them?

**Comment by spennyp** [comment]
Nice, this looks great! Make the changes I comments on.

Could you also deploy and comment out the top 3 to see the others will pick up and work?

**Comment by spennyp** [comment]
You will also need to add the new abi's, and make the changes to subgraph.yaml described in the docs for the price lib from Messari. You can find the abi's on etherscan by going to the respective contract (contract addresses are defined in the price libs constants.ts).

**Comment by arslanbekzhaparov** [comment]
I will reorganize some things

**Pull request closed without merging**
